# Generated by Django 2.0.3 on 2018-03-11 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(max_length=30, verbose_name='Coupon id')),
                ('firstname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Surname')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('bet1', models.CharField(max_length=3, verbose_name='Bet 1')),
                ('bet2', models.CharField(max_length=3, verbose_name='Bet 2')),
                ('bet3', models.CharField(max_length=3, verbose_name='Bet 3')),
                ('coupon_tour', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='game_tour', to='games.Games', to_field='games_tour')),
                ('match1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match1', to='games.Games', to_field='games_match1')),
                ('match2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match2', to='games.Games', to_field='games_match2')),
                ('match3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match3', to='games.Games', to_field='games_match3')),
            ],
        ),
    ]
