# Generated by Django 2.0.3 on 2018-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(help_text='Coupon id', max_length=30, verbose_name='Coupon id')),
                ('firstname', models.CharField(help_text='First Name', max_length=30, verbose_name='First Name')),
                ('lastname', models.CharField(help_text='Surname', max_length=30, verbose_name='Surname')),
                ('phone_number', models.CharField(help_text='Phone number', max_length=20, verbose_name='Phone number')),
                ('match1', models.CharField(help_text='First match', max_length=50, verbose_name='Match 1')),
                ('match2', models.CharField(help_text='Second match', max_length=50, verbose_name='Match 2')),
                ('match3', models.CharField(help_text='Third match', max_length=50, verbose_name='Match 3')),
                ('match4', models.CharField(help_text='Fourth match', max_length=50, verbose_name='Match 4')),
                ('match5', models.CharField(help_text='Fifth match', max_length=50, verbose_name='Match 5')),
                ('match6', models.CharField(help_text='Sixth match', max_length=50, verbose_name='Match 6')),
                ('match7', models.CharField(help_text='Seventh match', max_length=50, verbose_name='Match 7')),
                ('match8', models.CharField(help_text='Eighth match', max_length=50, verbose_name='Match 8')),
                ('match9', models.CharField(help_text='Ninth match', max_length=50, verbose_name='Match 9')),
                ('match10', models.CharField(help_text='Tenth match', max_length=50, verbose_name='Match 10')),
                ('match11', models.CharField(help_text='Eleventh match', max_length=50, verbose_name='Match 11')),
                ('match12', models.CharField(help_text='Twelfth match', max_length=50, verbose_name='Match 12')),
                ('bet1', models.CharField(help_text='First bet', max_length=3, verbose_name='Bet 1')),
                ('bet2', models.CharField(help_text='Second bet', max_length=3, verbose_name='Bet 2')),
                ('bet3', models.CharField(help_text='Third bet', max_length=3, verbose_name='Bet 3')),
                ('bet4', models.CharField(help_text='Fourth bet', max_length=3, verbose_name='Bet 4')),
                ('bet5', models.CharField(help_text='Fifth bet', max_length=3, verbose_name='Bet 5')),
                ('bet6', models.CharField(help_text='Sixth bet', max_length=3, verbose_name='Bet 6')),
                ('bet7', models.CharField(help_text='Seventh bet', max_length=3, verbose_name='Bet 7')),
                ('bet8', models.CharField(help_text='Eighth bet', max_length=3, verbose_name='Bet 8')),
                ('bet9', models.CharField(help_text='Ninth bet', max_length=3, verbose_name='Bet 9')),
                ('bet10', models.CharField(help_text='Tenth bet', max_length=3, verbose_name='Bet 10')),
                ('bet11', models.CharField(help_text='Eleventh bet', max_length=3, verbose_name='Bet 11')),
                ('bet12', models.CharField(help_text='Twelfth bet', max_length=3, verbose_name='Bet 12')),
            ],
        ),
    ]
