# Generated by Django 2.0.3 on 2018-03-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_id', models.CharField(max_length=30, verbose_name='Coupon id')),
                ('firstname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Surname')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('bet1', models.CharField(max_length=3, verbose_name='Bet 1')),
                ('bet2', models.CharField(max_length=3, verbose_name='Bet 2')),
                ('bet3', models.CharField(max_length=3, verbose_name='Bet 3')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_tour', models.CharField(default='0', max_length=30, unique=True, verbose_name='Tour')),
                ('games_match1', models.CharField(max_length=50, unique=True, verbose_name='Match 1')),
                ('games_match2', models.CharField(max_length=50, unique=True, verbose_name='Match 2')),
                ('games_match3', models.CharField(max_length=50, unique=True, verbose_name='Match 3')),
            ],
            options={
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_tour',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, related_name='game_tour', to='coupon.Games', to_field='games_tour'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='match1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match1', to='coupon.Games', to_field='games_match1'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='match2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match2', to='coupon.Games', to_field='games_match2'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='match3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match3', to='coupon.Games', to_field='games_match3'),
        ),
    ]
