# Generated by Django 2.0.3 on 2018-03-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Games'),
        ),
    ]
