# Generated by Django 2.0.3 on 2018-03-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20180311_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_id',
            field=models.CharField(max_length=30, verbose_name='Coupon id'),
        ),
    ]
