# Generated by Django 2.0.3 on 2018-03-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_tour', models.CharField(default='0', max_length=30, unique=True, verbose_name='Tour')),
                ('games_match1', models.CharField(max_length=50, unique=True, verbose_name='Match 1')),
                ('games_match2', models.CharField(max_length=50, unique=True, verbose_name='Match 2')),
                ('games_match3', models.CharField(max_length=50, unique=True, verbose_name='Match 3')),
            ],
            options={
                'verbose_name_plural': 'Games',
            },
        ),
    ]
