# Generated by Django 2.0.3 on 2018-03-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='id',
        ),
        migrations.AlterField(
            model_name='games',
            name='games_tour',
            field=models.CharField(default='0', max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Tour'),
        ),
    ]
